console.log(JSON.stringify({ ref: 'refs/heads/master',
    before: '1526adb4b4ffc9b7cf1e3806deead3221c1b7257',
    after: 'e7e88eb6037bd78a13b700307881c39e48985ff7',
    created: false,
    deleted: false,
    forced: false,
    base_ref: null,
    compare: 'https://github.com/nodebq/webhook/compare/1526adb4b4ff...e7e88eb6037b',
    commits:
        [ { id: 'e7e88eb6037bd78a13b700307881c39e48985ff7',
            tree_id: '7dc7c0b77329d59d0fd81d1dd0dba620c783333d',
            distinct: true,
            message: 'six',
            timestamp: '2016-04-25T10:41:17+08:00',
            url: 'https://github.com/nodebq/webhook/commit/e7e88eb6037bd78a13b700307881c39e48985ff7',
            author: [Object],
            committer: [Object],
            added: [Object],
            removed: [],
            modified: [Object] } ],
    head_commit:
    { id: 'e7e88eb6037bd78a13b700307881c39e48985ff7',
        tree_id: '7dc7c0b77329d59d0fd81d1dd0dba620c783333d',
        distinct: true,
        message: 'six',
        timestamp: '2016-04-25T10:41:17+08:00',
        url: 'https://github.com/nodebq/webhook/commit/e7e88eb6037bd78a13b700307881c39e48985ff7',
        author: { name: 'Qrex', email: '471597503@qq.com' },
        committer: { name: 'Qrex', email: '471597503@qq.com' },
        added: [ 'libs/test.js' ],
        removed: [],
        modified: [ 'controller/hook.js' ] },
    repository:
    { id: 56956352,
        name: 'webhook',
        full_name: 'nodebq/webhook',
        owner: { name: 'nodebq', email: 'momoxinshang@gmail.com' },
        private: false,
        html_url: 'https://github.com/nodebq/webhook',
        description: 'nothing,just test',
        fork: false,
        url: 'https://github.com/nodebq/webhook',
        forks_url: 'https://api.github.com/repos/nodebq/webhook/forks',
        keys_url: 'https://api.github.com/repos/nodebq/webhook/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/nodebq/webhook/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/nodebq/webhook/teams',
        hooks_url: 'https://api.github.com/repos/nodebq/webhook/hooks',
        issue_events_url: 'https://api.github.com/repos/nodebq/webhook/issues/events{/number}',
        events_url: 'https://api.github.com/repos/nodebq/webhook/events',
        assignees_url: 'https://api.github.com/repos/nodebq/webhook/assignees{/user}',
        branches_url: 'https://api.github.com/repos/nodebq/webhook/branches{/branch}',
        tags_url: 'https://api.github.com/repos/nodebq/webhook/tags',
        blobs_url: 'https://api.github.com/repos/nodebq/webhook/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/nodebq/webhook/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/nodebq/webhook/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/nodebq/webhook/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/nodebq/webhook/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/nodebq/webhook/languages',
        stargazers_url: 'https://api.github.com/repos/nodebq/webhook/stargazers',
        contributors_url: 'https://api.github.com/repos/nodebq/webhook/contributors',
        subscribers_url: 'https://api.github.com/repos/nodebq/webhook/subscribers',
        subscription_url: 'https://api.github.com/repos/nodebq/webhook/subscription',
        commits_url: 'https://api.github.com/repos/nodebq/webhook/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/nodebq/webhook/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/nodebq/webhook/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/nodebq/webhook/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/nodebq/webhook/contents/{+path}',
        compare_url: 'https://api.github.com/repos/nodebq/webhook/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/nodebq/webhook/merges',
        archive_url: 'https://api.github.com/repos/nodebq/webhook/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/nodebq/webhook/downloads',
        issues_url: 'https://api.github.com/repos/nodebq/webhook/issues{/number}',
        pulls_url: 'https://api.github.com/repos/nodebq/webhook/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/nodebq/webhook/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/nodebq/webhook/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/nodebq/webhook/labels{/name}',
        releases_url: 'https://api.github.com/repos/nodebq/webhook/releases{/id}',
        deployments_url: 'https://api.github.com/repos/nodebq/webhook/deployments',
        created_at: 1461476988,
        updated_at: '2016-04-24T05:58:56Z',
        pushed_at: 1461552089,
        git_url: 'git://github.com/nodebq/webhook.git',
        ssh_url: 'git@github.com:nodebq/webhook.git',
        clone_url: 'https://github.com/nodebq/webhook.git',
        svn_url: 'https://github.com/nodebq/webhook',
        homepage: null,
        size: 8,
        stargazers_count: 0,
        watchers_count: 0,
        language: 'JavaScript',
        has_issues: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        open_issues_count: 0,
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master',
        stargazers: 0,
        master_branch: 'master' },
    pusher: { name: 'nodebq', email: 'momoxinshang@gmail.com' },
    sender:
    { login: 'nodebq',
        id: 12863010,
        avatar_url: 'https://avatars.githubusercontent.com/u/12863010?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/nodebq',
        html_url: 'https://github.com/nodebq',
        followers_url: 'https://api.github.com/users/nodebq/followers',
        following_url: 'https://api.github.com/users/nodebq/following{/other_user}',
        gists_url: 'https://api.github.com/users/nodebq/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/nodebq/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/nodebq/subscriptions',
        organizations_url: 'https://api.github.com/users/nodebq/orgs',
        repos_url: 'https://api.github.com/users/nodebq/repos',
        events_url: 'https://api.github.com/users/nodebq/events{/privacy}',
        received_events_url: 'https://api.github.com/users/nodebq/received_events',
        type: 'User',
        site_admin: false } }));